version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - travellist

  db:
    image: mysql:5.7
    container_name: api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - travellist

  adminer:
      image: adminer:latest
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db_container
      ports:
        - 8080:8080

  nginx:
      image: nginx:1.18-alpine
      container_name: api-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./src:/var/www
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./docker/nginx/log:/var/log/nginx
      networks:
        - travellist
      command: nginx -g "daemon off;"
networks:
  travellist:
    driver: bridge
