version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: digitalocean.com/php
    tty: true
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      TZ: Europe/Moscow
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: 'mysql:5.7.31'
    container_name: api-db
    restart: unless-stopped
    tty: true
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: api_demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api_user
      MYSQL_PASSWORD: SomePassw0rd
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/scripts/:/docker-entrypoint-initdb.d/
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  adminer:
    image: adminer:latest
    tty: true
    ports:
        - 8080:8080
    networks:
      - app-network

  nginx:
      image: nginx:1.18-alpine
      container_name: api-nginx
      restart: unless-stopped
      tty: true
      ports:
        - 8000:80
      volumes:
        - ./src:/var/www
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./docker/nginx/log:/var/log/nginx
      command: nginx -g "daemon off;"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge